DEF const_value = 0

	const CATCHEM_BULBASAUR     ; $0
	const CATCHEM_CHARMANDER    ; $1
	const CATCHEM_SQUIRTLE      ; $2
	const CATCHEM_CATERPIE      ; $3
	const CATCHEM_WEEDLE        ; $4
	const CATCHEM_PIDGEY        ; $5
	const CATCHEM_RATTATA       ; $6
	const CATCHEM_SPEAROW       ; $7
	const CATCHEM_EKANS         ; $8
	const CATCHEM_PIKACHU       ; $9
	const CATCHEM_SANDSHREW     ; $a
	const CATCHEM_NIDORAN_F     ; $b
	const CATCHEM_NIDORAN_M     ; $c
	const CATCHEM_CLEFAIRY      ; $d
	const CATCHEM_VULPIX        ; $e
	const CATCHEM_JIGGLYPUFF    ; $f
	const CATCHEM_ZUBAT         ; $10
	const CATCHEM_ODDISH        ; $11
	const CATCHEM_PARAS         ; $12
	const CATCHEM_VENONAT       ; $13
	const CATCHEM_DIGLETT       ; $14
	const CATCHEM_MEOWTH        ; $15
	const CATCHEM_PSYDUCK       ; $16
	const CATCHEM_MANKEY        ; $17
	const CATCHEM_GROWLITHE     ; $18
	const CATCHEM_POLIWAG       ; $19
	const CATCHEM_ABRA          ; $1a
	const CATCHEM_MACHOP        ; $1b
	const CATCHEM_BELLSPROUT    ; $1c
	const CATCHEM_TENTACOOL     ; $1d
	const CATCHEM_GEODUDE       ; $1e
	const CATCHEM_PONYTA        ; $1f
	const CATCHEM_SLOWPOKE      ; $20
	const CATCHEM_MAGNEMITE     ; $21
	const CATCHEM_FARFETCH_D    ; $22
	const CATCHEM_DODUO         ; $23
	const CATCHEM_SEEL          ; $24
	const CATCHEM_GRIMER        ; $25
	const CATCHEM_SHELLDER      ; $26
	const CATCHEM_GASTLY        ; $27
	const CATCHEM_ONIX          ; $28
	const CATCHEM_DROWZEE       ; $29
	const CATCHEM_KRABBY        ; $2a
	const CATCHEM_VOLTORB       ; $2b
	const CATCHEM_EXEGGCUTE     ; $2c
	const CATCHEM_CUBONE        ; $2d
	const CATCHEM_TYROGUE       ; $2e
	const CATCHEM_LICKITUNG     ; $2f
	const CATCHEM_KOFFING       ; $30
	const CATCHEM_RHYHORN       ; $31
	const CATCHEM_CHANSEY       ; $32
	const CATCHEM_TANGELA       ; $33
	const CATCHEM_KANGASKHAN    ; $34
	const CATCHEM_HORSEA        ; $35
	const CATCHEM_SEADRA        ; $36
	const CATCHEM_GOLDEEN       ; $37
	const CATCHEM_STARYU        ; $38
	const CATCHEM_MR_MIME       ; $39
	const CATCHEM_SCYTHER       ; $3a
	const CATCHEM_JYNX          ; $3b
	const CATCHEM_ELECTABUZZ    ; $3c
	const CATCHEM_MAGMAR        ; $3d
	const CATCHEM_PINSIR        ; $3e
	const CATCHEM_TAUROS        ; $3f
	const CATCHEM_MAGIKARP      ; $40
	const CATCHEM_LAPRAS        ; $41
	const CATCHEM_DITTO         ; $42
	const CATCHEM_EEVEE         ; $43
	const CATCHEM_PORYGON       ; $44
	const CATCHEM_OMANYTE       ; $45
	const CATCHEM_KABUTO        ; $46
	const CATCHEM_AERODACTYL    ; $47
	const CATCHEM_SNORLAX       ; $48
	const CATCHEM_ARTICUNO      ; $49
	const CATCHEM_ZAPDOS        ; $4a
	const CATCHEM_MOLTRES       ; $4b
	const CATCHEM_DRATINI       ; $4c
	const CATCHEM_MEWTWO        ; $4d
	const CATCHEM_MEW           ; $4e
	const CATCHEM_CHIKORITA     ; $4f
	const CATCHEM_CYNDAQUIL     ; $50
	const CATCHEM_TOTODILE      ; $51
	const CATCHEM_SENTRET       ; $52
	const CATCHEM_HOOTHOOT      ; $53
	const CATCHEM_LEDYBA        ; $54
	const CATCHEM_SPINARAK      ; $55
	const CATCHEM_CHINCHOU      ; $56
	const CATCHEM_TOGEPI        ; $57
	const CATCHEM_NATU          ; $58
	const CATCHEM_MAREEP        ; $59
	const CATCHEM_MARILL        ; $5a
	const CATCHEM_SUDOWOODO     ; $5b
	const CATCHEM_HOPPIP        ; $5c
	const CATCHEM_AIPOM         ; $5d
	const CATCHEM_SUNKERN       ; $5e
	const CATCHEM_YANMA         ; $5f
	const CATCHEM_WOOPER        ; $60
	const CATCHEM_MURKROW       ; $61
	const CATCHEM_MISDREAVUS    ; $62
	const CATCHEM_UNOWN         ; $63
	const CATCHEM_WOBBUFFET     ; $64
	const CATCHEM_GIRAFARIG     ; $65
	const CATCHEM_PINECO        ; $66
	const CATCHEM_DUNSPARCE     ; $67
	const CATCHEM_GLIGAR        ; $68
	const CATCHEM_SNUBBULL      ; $69
	const CATCHEM_QWILFISH      ; $6a
	const CATCHEM_SHUCKLE       ; $6b
	const CATCHEM_HERACROSS     ; $6c
	const CATCHEM_SNEASEL       ; $6d
	const CATCHEM_TEDDIURSA     ; $6e
	const CATCHEM_SLUGMA        ; $6f
	const CATCHEM_SWINUB        ; $70
	const CATCHEM_CORSOLA       ; $71
	const CATCHEM_REMORAID      ; $72
	const CATCHEM_DELIBIRD      ; $73
	const CATCHEM_MANTINE       ; $74
	const CATCHEM_SKARMORY      ; $75
	const CATCHEM_HOUNDOUR      ; $76
	const CATCHEM_PHANPY        ; $77
	const CATCHEM_STANTLER      ; $78
	const CATCHEM_SMEARGLE      ; $79
	const CATCHEM_MILTANK       ; $7a
	const CATCHEM_RAIKOU        ; $7b
	const CATCHEM_ENTEI         ; $7c
	const CATCHEM_SUICUNE       ; $7d
	const CATCHEM_LARVITAR      ; $7e
	const CATCHEM_LUGIA         ; $7f
	const CATCHEM_HO_OH         ; $80
	const CATCHEM_CELEBI        ; $81
	const CATCHEM_TREECKO       ; $82
	const CATCHEM_TORCHIC       ; $83
	const CATCHEM_MUDKIP        ; $84
	const CATCHEM_POOCHYENA     ; $85
	const CATCHEM_ZIGZAGOON     ; $86
	const CATCHEM_WURMPLE       ; $87
	const CATCHEM_LOTAD         ; $88
	const CATCHEM_SEEDOT        ; $89
	const CATCHEM_TAILLOW       ; $8A
	const CATCHEM_WINGULL       ; $8B
	const CATCHEM_RALTS         ; $8C
	const CATCHEM_SURSKIT       ; $8D
	const CATCHEM_SHROOMISH     ; $8E
	const CATCHEM_SLAKOTH       ; $8F
	const CATCHEM_NINCADA       ; $90
	const CATCHEM_WHISMUR       ; $91
	const CATCHEM_MAKUHITA      ; $92
	const CATCHEM_NOSEPASS      ; $93
	const CATCHEM_SKITTY        ; $94
	const CATCHEM_SABLEYE       ; $95
	const CATCHEM_MAWILE        ; $96
	const CATCHEM_ARON          ; $97
	const CATCHEM_MEDITITE      ; $98
	const CATCHEM_ELECTRIKE     ; $99
	const CATCHEM_PLUSLE        ; $9A
	const CATCHEM_MINUN         ; $9B
	const CATCHEM_VOLBEAT       ; $9C
	const CATCHEM_ILLUMISE      ; $9D
	const CATCHEM_ROSELIA       ; $9E
	const CATCHEM_GULPIN        ; $9F
	const CATCHEM_CARVANHA      ; $A0
	const CATCHEM_WAILMER       ; $A1
	const CATCHEM_NUMEL         ; $A2
	const CATCHEM_TORKOAL       ; $A3
	const CATCHEM_SPOINK        ; $A4
	const CATCHEM_SPINDA        ; $A5
	const CATCHEM_TRAPINCH      ; $A6
	const CATCHEM_CACNEA        ; $A7
	const CATCHEM_SWABLU        ; $A8
	const CATCHEM_ZANGOOSE      ; $A9
	const CATCHEM_SEVIPER       ; $AA
	const CATCHEM_LUNATONE      ; $AB
	const CATCHEM_SOLROCK       ; $AC
	const CATCHEM_BARBOACH      ; $AD
	const CATCHEM_CORPHISH      ; $AE
	const CATCHEM_BALTOY        ; $AF
	const CATCHEM_LILEEP        ; $B0
	const CATCHEM_ANORITH       ; $B1
	const CATCHEM_FEEBAS        ; $B2
	const CATCHEM_CASTFORM      ; $B3
	const CATCHEM_KECLEON       ; $B4
	const CATCHEM_SHUPPET       ; $B5
	const CATCHEM_DUSKULL       ; $B6
	const CATCHEM_TROPIUS       ; $B7
	const CATCHEM_CHIMECHO      ; $B8
	const CATCHEM_ABSOL         ; $B9
	const CATCHEM_SNORUNT       ; $BA
	const CATCHEM_SPHEAL        ; $BB
	const CATCHEM_CLAMPERL      ; $BC
	const CATCHEM_RELICANTH     ; $BD
	const CATCHEM_LUVDISC       ; $BE
	const CATCHEM_BAGON         ; $BF
	const CATCHEM_BELDUM        ; $C0
	const CATCHEM_REGIROCK      ; $C1
	const CATCHEM_REGICE        ; $C2
	const CATCHEM_REGISTEEL     ; $C3
	const CATCHEM_LATIAS        ; $C4
	const CATCHEM_LATIOS        ; $C5
	const CATCHEM_KYOGRE        ; $C6
	const CATCHEM_GROUDON       ; $C7
	const CATCHEM_RAYQUAZA      ; $C8
	const CATCHEM_JIRACHI       ; $C9
	const CATCHEM_DEOXYS        ; $CA
