const_value = 0
	
	const EVOLINE_BULBASAUR     ; $0
	const EVOLINE_CHARMANDER    ; $1
	const EVOLINE_SQUIRTLE      ; $2
	const EVOLINE_CATERPIE      ; $3
	const EVOLINE_WEEDLE        ; $4
	const EVOLINE_PIDGEY        ; $5
	const EVOLINE_RATTATA       ; $6
	const EVOLINE_SPEAROW       ; $7
	const EVOLINE_EKANS         ; $8
	const EVOLINE_PIKACHU       ; $9
	const EVOLINE_SANDSHREW     ; $a
	const EVOLINE_NIDORAN_F     ; $b
	const EVOLINE_NIDORAN_M     ; $c
	const EVOLINE_CLEFAIRY      ; $d
	const EVOLINE_VULPIX        ; $e
	const EVOLINE_JIGGLYPUFF    ; $f
	const EVOLINE_ZUBAT         ; $10
	const EVOLINE_ODDISH        ; $11
	const EVOLINE_PARAS         ; $12
	const EVOLINE_VENONAT       ; $13
	const EVOLINE_DIGLETT       ; $14
	const EVOLINE_MEOWTH        ; $15
	const EVOLINE_PSYDUCK       ; $16
	const EVOLINE_MANKEY        ; $17
	const EVOLINE_GROWLITHE     ; $18
	const EVOLINE_POLIWAG       ; $19
	const EVOLINE_ABRA          ; $1a
	const EVOLINE_MACHOP        ; $1b
	const EVOLINE_BELLSPROUT    ; $1c
	const EVOLINE_TENTACOOL     ; $1d
	const EVOLINE_GEODUDE       ; $1e
	const EVOLINE_PONYTA        ; $1f
	const EVOLINE_SLOWPOKE      ; $20
	const EVOLINE_MAGNEMITE     ; $21
	const EVOLINE_FARFETCH_D    ; $22
	const EVOLINE_DODUO         ; $23
	const EVOLINE_SEEL          ; $24
	const EVOLINE_GRIMER        ; $25
	const EVOLINE_SHELLDER      ; $26
	const EVOLINE_GASTLY        ; $27
	const EVOLINE_ONIX          ; $28
	const EVOLINE_DROWZEE       ; $29
	const EVOLINE_KRABBY        ; $2a
	const EVOLINE_VOLTORB       ; $2b
	const EVOLINE_EXEGGCUTE     ; $2c
	const EVOLINE_CUBONE        ; $2d
	const EVOLINE_TYROGUE       ; $2e
	const EVOLINE_LICKITUNG     ; $2f
	const EVOLINE_KOFFING       ; $30
	const EVOLINE_RHYHORN       ; $31
	const EVOLINE_CHANSEY       ; $32
	const EVOLINE_TANGELA       ; $33
	const EVOLINE_KANGASKHAN    ; $34
	const EVOLINE_HORSEA        ; $35
	const EVOLINE_GOLDEEN       ; $36
	const EVOLINE_STARYU        ; $37
	const EVOLINE_MR_MIME       ; $38
	const EVOLINE_SCYTHER       ; $39
	const EVOLINE_JYNX          ; $3a
	const EVOLINE_ELECTABUZZ    ; $3b
	const EVOLINE_MAGMAR        ; $3c
	const EVOLINE_PINSIR        ; $3d
	const EVOLINE_TAUROS        ; $3e
	const EVOLINE_MAGIKARP      ; $3f
	const EVOLINE_LAPRAS        ; $40
	const EVOLINE_DITTO         ; $41
	const EVOLINE_EEVEE         ; $42
	const EVOLINE_PORYGON       ; $43
	const EVOLINE_OMANYTE       ; $44
	const EVOLINE_KABUTO        ; $45
	const EVOLINE_AERODACTYL    ; $46
	const EVOLINE_SNORLAX       ; $47
	const EVOLINE_ARTICUNO      ; $48
	const EVOLINE_ZAPDOS        ; $49
	const EVOLINE_MOLTRES       ; $4a
	const EVOLINE_DRATINI       ; $4b
	const EVOLINE_MEWTWO        ; $4c
	const EVOLINE_MEW           ; $4d
	const EVOLINE_CHIKORITA     ; $4e
	const EVOLINE_CYNDAQUIL     ; $4f
	const EVOLINE_TOTODILE      ; $50
	const EVOLINE_SENTRET       ; $51
	const EVOLINE_HOOTHOOT      ; $52
	const EVOLINE_LEDYBA        ; $53
	const EVOLINE_SPINARAK      ; $54
	const EVOLINE_CHINCHOU      ; $55
	const EVOLINE_TOGEPI        ; $56
	const EVOLINE_NATU          ; $57
	const EVOLINE_MAREEP        ; $58
	const EVOLINE_MARILL        ; $59
	const EVOLINE_SUDOWOODO     ; $5a
	const EVOLINE_HOPPIP        ; $5b
	const EVOLINE_AIPOM         ; $5c
	const EVOLINE_SUNKERN       ; $5d
	const EVOLINE_YANMA         ; $5e
	const EVOLINE_WOOPER        ; $5f
	const EVOLINE_MURKROW       ; $60
	const EVOLINE_MISDREAVUS    ; $61
	const EVOLINE_UNOWN         ; $62
	const EVOLINE_WOBBUFFET     ; $63
	const EVOLINE_GIRAFARIG     ; $64
	const EVOLINE_PINECO        ; $65
	const EVOLINE_DUNSPARCE     ; $66
	const EVOLINE_GLIGAR        ; $67
	const EVOLINE_SNUBBULL      ; $68
	const EVOLINE_QWILFISH      ; $69
	const EVOLINE_SHUCKLE       ; $6a
	const EVOLINE_HERACROSS     ; $6b
	const EVOLINE_SNEASEL       ; $6c
	const EVOLINE_TEDDIURSA     ; $6d
	const EVOLINE_SLUGMA        ; $6e
	const EVOLINE_SWINUB        ; $6f
	const EVOLINE_CORSOLA       ; $70
	const EVOLINE_REMORAID      ; $71
	const EVOLINE_DELIBIRD      ; $72
	const EVOLINE_MANTINE       ; $73
	const EVOLINE_SKARMORY      ; $74
	const EVOLINE_HOUNDOUR      ; $75
	const EVOLINE_PHANPY        ; $76
	const EVOLINE_STANTLER      ; $77
	const EVOLINE_SMEARGLE      ; $78
	const EVOLINE_MILTANK       ; $79
	const EVOLINE_RAIKOU        ; $7a
	const EVOLINE_ENTEI         ; $7b
	const EVOLINE_SUICUNE       ; $7c
	const EVOLINE_LARVITAR      ; $7d
	const EVOLINE_LUGIA         ; $7e
	const EVOLINE_HO_OH         ; $7f
	const EVOLINE_CELEBI        ; $80
