const_value = 0
	
	const EVOLINE_BULBASAUR     ; $0
	const EVOLINE_CHARMANDER    ; $1
	const EVOLINE_SQUIRTLE      ; $2
	const EVOLINE_CATERPIE      ; $3
	const EVOLINE_WEEDLE        ; $4
	const EVOLINE_PIDGEY        ; $5
	const EVOLINE_RATTATA       ; $6
	const EVOLINE_SPEAROW       ; $7
	const EVOLINE_EKANS         ; $8
	const EVOLINE_PIKACHU       ; $9
	const EVOLINE_SANDSHREW     ; $a
	const EVOLINE_NIDORAN_F     ; $b
	const EVOLINE_NIDORAN_M     ; $c
	const EVOLINE_CLEFAIRY      ; $d
	const EVOLINE_VULPIX        ; $e
	const EVOLINE_JIGGLYPUFF    ; $f
	const EVOLINE_ZUBAT         ; $10
	const EVOLINE_ODDISH        ; $11
	const EVOLINE_PARAS         ; $12
	const EVOLINE_VENONAT       ; $13
	const EVOLINE_DIGLETT       ; $14
	const EVOLINE_MEOWTH        ; $15
	const EVOLINE_PSYDUCK       ; $16
	const EVOLINE_MANKEY        ; $17
	const EVOLINE_GROWLITHE     ; $18
	const EVOLINE_POLIWAG       ; $19
	const EVOLINE_ABRA          ; $1a
	const EVOLINE_MACHOP        ; $1b
	const EVOLINE_BELLSPROUT    ; $1c
	const EVOLINE_TENTACOOL     ; $1d
	const EVOLINE_GEODUDE       ; $1e
	const EVOLINE_PONYTA        ; $1f
	const EVOLINE_SLOWPOKE      ; $20
	const EVOLINE_MAGNEMITE     ; $21
	const EVOLINE_FARFETCH_D    ; $22
	const EVOLINE_DODUO         ; $23
	const EVOLINE_SEEL          ; $24
	const EVOLINE_GRIMER        ; $25
	const EVOLINE_SHELLDER      ; $26
	const EVOLINE_GASTLY        ; $27
	const EVOLINE_ONIX          ; $28
	const EVOLINE_DROWZEE       ; $29
	const EVOLINE_KRABBY        ; $2a
	const EVOLINE_VOLTORB       ; $2b
	const EVOLINE_EXEGGCUTE     ; $2c
	const EVOLINE_CUBONE        ; $2d
	const EVOLINE_TYROGUE       ; $2e
	const EVOLINE_LICKITUNG     ; $2f
	const EVOLINE_KOFFING       ; $30
	const EVOLINE_RHYHORN       ; $31
	const EVOLINE_CHANSEY       ; $32
	const EVOLINE_TANGELA       ; $33
	const EVOLINE_KANGASKHAN    ; $34
	const EVOLINE_HORSEA        ; $35
	const EVOLINE_SEADRA        ; $36
	const EVOLINE_GOLDEEN       ; $37
	const EVOLINE_STARYU        ; $38
	const EVOLINE_MR_MIME       ; $39
	const EVOLINE_SCYTHER       ; $3a
	const EVOLINE_JYNX          ; $3b
	const EVOLINE_ELECTABUZZ    ; $3c
	const EVOLINE_MAGMAR        ; $3d
	const EVOLINE_PINSIR        ; $3e
	const EVOLINE_TAUROS        ; $3f
	const EVOLINE_MAGIKARP      ; $40
	const EVOLINE_LAPRAS        ; $41
	const EVOLINE_DITTO         ; $42
	const EVOLINE_EEVEE         ; $43
	const EVOLINE_PORYGON       ; $44
	const EVOLINE_OMANYTE       ; $45
	const EVOLINE_KABUTO        ; $46
	const EVOLINE_AERODACTYL    ; $47
	const EVOLINE_SNORLAX       ; $48
	const EVOLINE_ARTICUNO      ; $49
	const EVOLINE_ZAPDOS        ; $4a
	const EVOLINE_MOLTRES       ; $4b
	const EVOLINE_DRATINI       ; $4c
	const EVOLINE_MEWTWO        ; $4d
	const EVOLINE_MEW           ; $4e
	const EVOLINE_CHIKORITA     ; $4f
	const EVOLINE_CYNDAQUIL     ; $50
	const EVOLINE_TOTODILE      ; $51
	const EVOLINE_SENTRET       ; $52
	const EVOLINE_HOOTHOOT      ; $53
	const EVOLINE_LEDYBA        ; $54
	const EVOLINE_SPINARAK      ; $55
	const EVOLINE_CHINCHOU      ; $56
	const EVOLINE_TOGEPI        ; $57
	const EVOLINE_NATU          ; $58
	const EVOLINE_MAREEP        ; $59
	const EVOLINE_MARILL        ; $5a
	const EVOLINE_SUDOWOODO     ; $5b
	const EVOLINE_HOPPIP        ; $5c
	const EVOLINE_AIPOM         ; $5d
	const EVOLINE_SUNKERN       ; $5e
	const EVOLINE_YANMA         ; $5f
	const EVOLINE_WOOPER        ; $60
	const EVOLINE_MURKROW       ; $61
	const EVOLINE_MISDREAVUS    ; $62
	const EVOLINE_UNOWN         ; $63
	const EVOLINE_WOBBUFFET     ; $64
	const EVOLINE_GIRAFARIG     ; $65
	const EVOLINE_PINECO        ; $66
	const EVOLINE_DUNSPARCE     ; $67
	const EVOLINE_GLIGAR        ; $68
	const EVOLINE_SNUBBULL      ; $69
	const EVOLINE_QWILFISH      ; $6a
	const EVOLINE_SHUCKLE       ; $6b
	const EVOLINE_HERACROSS     ; $6c
	const EVOLINE_SNEASEL       ; $6d
	const EVOLINE_TEDDIURSA     ; $6e
	const EVOLINE_SLUGMA        ; $6f
	const EVOLINE_SWINUB        ; $70
	const EVOLINE_CORSOLA       ; $71
	const EVOLINE_REMORAID      ; $72
	const EVOLINE_DELIBIRD      ; $73
	const EVOLINE_MANTINE       ; $74
	const EVOLINE_SKARMORY      ; $75
	const EVOLINE_HOUNDOUR      ; $76
	const EVOLINE_PHANPY        ; $77
	const EVOLINE_STANTLER      ; $78
	const EVOLINE_SMEARGLE      ; $79
	const EVOLINE_MILTANK       ; $7a
	const EVOLINE_RAIKOU        ; $7b
	const EVOLINE_ENTEI         ; $7c
	const EVOLINE_SUICUNE       ; $7d
	const EVOLINE_LARVITAR      ; $7e
	const EVOLINE_LUGIA         ; $7f
	const EVOLINE_HO_OH         ; $80
	const EVOLINE_CELEBI        ; $81
	const EVOLINE_TREECKO       ; $82
	const EVOLINE_TORCHIC       ; $83
	const EVOLINE_MUDKIP        ; $84
	const EVOLINE_POOCHYENA     ; $85
	const EVOLINE_ZIGZAGOON     ; $86
	const EVOLINE_WURMPLE       ; $87
	const EVOLINE_LOTAD         ; $88
	const EVOLINE_SEEDOT        ; $89
	const EVOLINE_TAILLOW       ; $8A
	const EVOLINE_WINGULL       ; $8B
	const EVOLINE_RALTS         ; $8C
	const EVOLINE_SURSKIT       ; $8D
	const EVOLINE_SHROOMISH     ; $8E
	const EVOLINE_SLAKOTH       ; $8F
	const EVOLINE_NINCADA       ; $90
	const EVOLINE_WHISMUR       ; $91
	const EVOLINE_MAKUHITA      ; $92
	const EVOLINE_NOSEPASS      ; $93
	const EVOLINE_SKITTY        ; $94
	const EVOLINE_SABLEYE       ; $95
	const EVOLINE_MAWILE        ; $96
	const EVOLINE_ARON          ; $97
	const EVOLINE_MEDITITE      ; $98
	const EVOLINE_ELECTRIKE     ; $99
	const EVOLINE_PLUSLE        ; $9A
	const EVOLINE_MINUN         ; $9B
	const EVOLINE_VOLBEAT       ; $9C
	const EVOLINE_ILLUMISE      ; $9D
	const EVOLINE_ROSELIA       ; $9E
	const EVOLINE_GULPIN        ; $9F
	const EVOLINE_CARVANHA      ; $A0
	const EVOLINE_WAILMER       ; $A1
	const EVOLINE_NUMEL         ; $A2
	const EVOLINE_TORKOAL       ; $A3
	const EVOLINE_SPOINK        ; $A4
	const EVOLINE_SPINDA        ; $A5
	const EVOLINE_TRAPINCH      ; $A6
	const EVOLINE_CACNEA        ; $A7
	const EVOLINE_SWABLU        ; $A8
	const EVOLINE_ZANGOOSE      ; $A9
	const EVOLINE_SEVIPER       ; $AA
	const EVOLINE_LUNATONE      ; $AB
	const EVOLINE_SOLROCK       ; $AC
	const EVOLINE_BARBOACH      ; $AD
	const EVOLINE_CORPHISH      ; $AE
	const EVOLINE_BALTOY        ; $AF
	const EVOLINE_LILEEP        ; $B0
	const EVOLINE_ANORITH       ; $B1
	const EVOLINE_FEEBAS        ; $B2
	const EVOLINE_CASTFORM      ; $B3
	const EVOLINE_KECLEON       ; $B4
	const EVOLINE_SHUPPET       ; $B5
	const EVOLINE_DUSKULL       ; $B6
	const EVOLINE_TROPIUS       ; $B7
	const EVOLINE_CHIMECHO      ; $B8
	const EVOLINE_ABSOL         ; $B9
	const EVOLINE_SNORUNT       ; $BA
	const EVOLINE_SPHEAL        ; $BB
	const EVOLINE_CLAMPERL      ; $BC
	const EVOLINE_RELICANTH     ; $BD
	const EVOLINE_LUVDISC       ; $BE
	const EVOLINE_BAGON         ; $BF
	const EVOLINE_BELDUM        ; $C0
	const EVOLINE_REGIROCK      ; $C1
	const EVOLINE_REGICE        ; $C2
	const EVOLINE_REGISTEEL     ; $C3
	const EVOLINE_LATIAS        ; $C4
	const EVOLINE_LATIOS        ; $C5
	const EVOLINE_KYOGRE        ; $C6
	const EVOLINE_GROUDON       ; $C7
	const EVOLINE_RAYQUAZA      ; $C8
	const EVOLINE_JIRACHI       ; $C9
	const EVOLINE_DEOXYS        ; $CA
