DEF const_value = 0

	const PALLET_TOWN        ; $0
	const VIRIDIAN_CITY      ; $1
	const VIRIDIAN_FOREST    ; $2
	const PEWTER_CITY        ; $3
	const MT_MOON            ; $4
	const CERULEAN_CITY      ; $5
	const VERMILION_SEASIDE  ; $6
	const VERMILION_STREETS  ; $7
	const ROCK_MOUNTAIN      ; $8
	const LAVENDER_TOWN      ; $9
	const CELADON_CITY       ; $a
	const CYCLING_ROAD       ; $b
	const FUCHSIA_CITY       ; $c
	const SAFARI_ZONE        ; $d
	const SAFFRON_CITY       ; $e
	const SEAFOAM_ISLANDS    ; $f
	const CINNABAR_ISLAND    ; $10
	const INDIGO_PLATEAU     ; $11

	const NEW_BARK_TOWN      ; $12
	const VIOLET_CITY        ; $13
	const RUINS_OF_ALPH      ; $14
	const DARK_CAVE          ; $15
	const LAKE_OF_RAGE       ; $16
	const MAHOGANY_TOWN      ; $17
	const ECRUTEAK_CITY      ; $18
	const AZALEA_TOWN        ; $19
	const ILEX_FOREST        ; $1A
	const GOLDENROD_CITY     ; $1B
	const NATIONAL_PARK      ; $1C
	const OLIVINE_CITY       ; $1D
	const ICE_PATH           ; $1E
	const MT_MORTAR          ; $1F
	const BURNED_TOWER       ; $20
	const TIN_TOWER          ; $21
	const WHIRL_ISLANDS      ; $22
	const BLACKTHORN_CITY    ; $23
	const MT_SILVER          ; $24
