DEF const_value = 1

	const BULBASAUR   ; $1
	const IVYSAUR     ; $2
	const VENUSAUR    ; $3
	const CHARMANDER  ; $4
	const CHARMELEON  ; $5
	const CHARIZARD   ; $6
	const SQUIRTLE    ; $7
	const WARTORTLE   ; $8
	const BLASTOISE   ; $9
	const CATERPIE    ; $a
	const METAPOD     ; $b
	const BUTTERFREE  ; $c
	const WEEDLE      ; $d
	const KAKUNA      ; $e
	const BEEDRILL    ; $f
	const PIDGEY      ; $10
	const PIDGEOTTO   ; $11
	const PIDGEOT     ; $12
	const RATTATA     ; $13
	const RATICATE    ; $14
	const SPEAROW     ; $15
	const FEAROW      ; $16
	const EKANS       ; $17
	const ARBOK       ; $18
	const PIKACHU     ; $19
	const RAICHU      ; $1a
	const SANDSHREW   ; $1b
	const SANDSLASH   ; $1c
	const NIDORAN_F   ; $1d
	const NIDORINA    ; $1e
	const NIDOQUEEN   ; $1f
	const NIDORAN_M   ; $20
	const NIDORINO    ; $21
	const NIDOKING    ; $22
	const CLEFAIRY    ; $23
	const CLEFABLE    ; $24
	const VULPIX      ; $25
	const NINETALES   ; $26
	const JIGGLYPUFF  ; $27
	const WIGGLYTUFF  ; $28
	const ZUBAT       ; $29
	const GOLBAT      ; $2a
	const ODDISH      ; $2b
	const GLOOM       ; $2c
	const VILEPLUME   ; $2d
	const PARAS       ; $2e
	const PARASECT    ; $2f
	const VENONAT     ; $30
	const VENOMOTH    ; $31
	const DIGLETT     ; $32
	const DUGTRIO     ; $33
	const MEOWTH      ; $34
	const PERSIAN     ; $35
	const PSYDUCK     ; $36
	const GOLDUCK     ; $37
	const MANKEY      ; $38
	const PRIMEAPE    ; $39
	const GROWLITHE   ; $3a
	const ARCANINE    ; $3b
	const POLIWAG     ; $3c
	const POLIWHIRL   ; $3d
	const POLIWRATH   ; $3e
	const ABRA        ; $3f
	const KADABRA     ; $40
	const ALAKAZAM    ; $41
	const MACHOP      ; $42
	const MACHOKE     ; $43
	const MACHAMP     ; $44
	const BELLSPROUT  ; $45
	const WEEPINBELL  ; $46
	const VICTREEBEL  ; $47
	const TENTACOOL   ; $48
	const TENTACRUEL  ; $49
	const GEODUDE     ; $4a
	const GRAVELER    ; $4b
	const GOLEM       ; $4c
	const PONYTA      ; $4d
	const RAPIDASH    ; $4e
	const SLOWPOKE    ; $4f
	const SLOWBRO     ; $50
	const MAGNEMITE   ; $51
	const MAGNETON    ; $52
	const FARFETCH_D  ; $53
	const DODUO       ; $54
	const DODRIO      ; $55
	const SEEL        ; $56
	const DEWGONG     ; $57
	const GRIMER      ; $58
	const MUK         ; $59
	const SHELLDER    ; $5a
	const CLOYSTER    ; $5b
	const GASTLY      ; $5c
	const HAUNTER     ; $5d
	const GENGAR      ; $5e
	const ONIX        ; $5f
	const DROWZEE     ; $60
	const HYPNO       ; $61
	const KRABBY      ; $62
	const KINGLER     ; $63
	const VOLTORB     ; $64
	const ELECTRODE   ; $65
	const EXEGGCUTE   ; $66
	const EXEGGUTOR   ; $67
	const CUBONE      ; $68
	const MAROWAK     ; $69
	const HITMONLEE   ; $6a
	const HITMONCHAN  ; $6b
	const LICKITUNG   ; $6c
	const KOFFING     ; $6d
	const WEEZING     ; $6e
	const RHYHORN     ; $6f
	const RHYDON      ; $70
	const CHANSEY     ; $71
	const TANGELA     ; $72
	const KANGASKHAN  ; $73
	const HORSEA      ; $74
	const SEADRA      ; $75
	const GOLDEEN     ; $76
	const SEAKING     ; $77
	const STARYU      ; $78
	const STARMIE     ; $79
	const MR_MIME     ; $7a
	const SCYTHER     ; $7b
	const JYNX        ; $7c
	const ELECTABUZZ  ; $7d
	const MAGMAR      ; $7e
	const PINSIR      ; $7f
	const TAUROS      ; $80
	const MAGIKARP    ; $81
	const GYARADOS    ; $82
	const LAPRAS      ; $83
	const DITTO       ; $84
	const EEVEE       ; $85
	const VAPOREON    ; $86
	const JOLTEON     ; $87
	const FLAREON     ; $88
	const PORYGON     ; $89
	const OMANYTE     ; $8a
	const OMASTAR     ; $8b
	const KABUTO      ; $8c
	const KABUTOPS    ; $8d
	const AERODACTYL  ; $8e
	const SNORLAX     ; $8f
	const ARTICUNO    ; $90
	const ZAPDOS      ; $91
	const MOLTRES     ; $92
	const DRATINI     ; $93
	const DRAGONAIR   ; $94
	const DRAGONITE   ; $95
	const MEWTWO      ; $96
	const MEW         ; $97
	const CHIKORITA   ; $98
	const BAYLEEF     ; $99
	const MEGANIUM    ; $9a
	const CYNDAQUIL   ; $9b
	const QUILAVA     ; $9c
	const TYPHLOSION  ; $9d
	const TOTODILE    ; $9e
	const CROCONAW    ; $9f
	const FERALIGATR  ; $a0
	const SENTRET     ; $a1
	const FURRET      ; $a2
	const HOOTHOOT    ; $a3
	const NOCTOWL     ; $a4
	const LEDYBA      ; $a5
	const LEDIAN      ; $a6
	const SPINARAK    ; $a7
	const ARIADOS     ; $a8
	const CROBAT      ; $a9
	const CHINCHOU    ; $aa
	const LANTURN     ; $ab
	const PICHU       ; $ac
	const CLEFFA      ; $ad
	const IGGLYBUFF   ; $ae
	const TOGEPI      ; $af
	const TOGETIC     ; $b0
	const NATU        ; $b1
	const XATU        ; $b2
	const MAREEP      ; $b3
	const FLAAFFY     ; $b4
	const AMPHAROS    ; $b5
	const BELLOSSOM   ; $b6
	const MARILL      ; $b7
	const AZUMARILL   ; $b8
	const SUDOWOODO   ; $b9
	const POLITOED    ; $ba
	const HOPPIP      ; $bb
	const SKIPLOOM    ; $bc
	const JUMPLUFF    ; $bd
	const AIPOM       ; $be
	const SUNKERN     ; $bf
	const SUNFLORA    ; $c0
	const YANMA       ; $c1
	const WOOPER      ; $c2
	const QUAGSIRE    ; $c3
	const ESPEON      ; $c4
	const UMBREON     ; $c5
	const MURKROW     ; $c6
	const SLOWKING    ; $c7
	const MISDREAVUS  ; $c8
	const UNOWN       ; $c9
	const WOBBUFFET   ; $ca
	const GIRAFARIG   ; $cb
	const PINECO      ; $cc
	const FORRETRESS  ; $cd
	const DUNSPARCE   ; $ce
	const GLIGAR      ; $cf
	const STEELIX     ; $d0
	const SNUBBULL    ; $d1
	const GRANBULL    ; $d2
	const QWILFISH    ; $d3
	const SCIZOR      ; $d4
	const SHUCKLE     ; $d5
	const HERACROSS   ; $d6
	const SNEASEL     ; $d7
	const TEDDIURSA   ; $d8
	const URSARING    ; $d9
	const SLUGMA      ; $da
	const MAGCARGO    ; $db
	const SWINUB      ; $dc
	const PILOSWINE   ; $dd
	const CORSOLA     ; $de
	const REMORAID    ; $df
	const OCTILLERY   ; $e0
	const DELIBIRD    ; $e1
	const MANTINE     ; $e2
	const SKARMORY    ; $e3
	const HOUNDOUR    ; $e4
	const HOUNDOOM    ; $e5
	const KINGDRA     ; $e6
	const PHANPY      ; $e7
	const DONPHAN     ; $e8
	const PORYGON2    ; $e9
	const STANTLER    ; $ea
	const SMEARGLE    ; $eb
	const TYROGUE     ; $ec
	const HITMONTOP   ; $ed
	const SMOOCHUM    ; $ee
	const ELEKID      ; $ef
	const MAGBY       ; $f0
	const MILTANK     ; $f1
	const BLISSEY     ; $f2
	const RAIKOU      ; $f3
	const ENTEI       ; $f4
	const SUICUNE     ; $f5
	const LARVITAR    ; $f6
	const PUPITAR     ; $f7
	const TYRANITAR   ; $f8
	const LUGIA       ; $f9
	const HO_OH       ; $fa
	const CELEBI      ; $fb
	const TREECKO     ; $fc
	const GROVYLE     ; $fd
	const SCEPTILE    ; $fe
	const TORCHIC     ; $ff
	const COMBUSKEN   ; $100
	const BLAZIKEN    ; $101
	const MUDKIP      ; $102
	const MARSHTOMP   ; $103
	const SWAMPERT    ; $104
	const POOCHYENA   ; $105
	const MIGHTYENA   ; $106
	const ZIGZAGOON   ; $107
	const LINOONE     ; $108
	const WURMPLE     ; $109
	const SILCOON     ; $10A
	const BEAUTIFLY   ; $10B
	const CASCOON     ; $10C
	const DUSTOX      ; $10D
	const LOTAD       ; $10E
	const LOMBRE      ; $10F
	const LUDICOLO    ; $110
	const SEEDOT      ; $111
	const NUZLEAF     ; $112
	const SHIFTRY     ; $113
	const TAILLOW     ; $114
	const SWELLOW     ; $115
	const WINGULL     ; $116
	const PELIPPER    ; $117
	const RALTS       ; $118
	const KIRLIA      ; $119
	const GARDEVOIR   ; $11A
	const SURSKIT     ; $11B
	const MASQUERAIN  ; $11C
	const SHROOMISH   ; $11D
	const BRELOOM     ; $11E
	const SLAKOTH     ; $11F
	const VIGOROTH    ; $120
	const SLAKING     ; $121
	const NINCADA     ; $122
	const NINJASK     ; $123
	const SHEDINJA    ; $124
	const WHISMUR     ; $125
	const LOUDRED     ; $126
	const EXPLOUD     ; $127
	const MAKUHITA    ; $128
	const HARIYAMA    ; $129
	const AZURILL     ; $12A
	const NOSEPASS    ; $12B
	const SKITTY      ; $12C
	const DELCATTY    ; $12D
	const SABLEYE     ; $12E
	const MAWILE      ; $12F
	const ARON        ; $130
	const LAIRON      ; $131
	const AGGRON      ; $132
	const MEDITITE    ; $133
	const MEDICHAM    ; $134
	const ELECTRIKE   ; $135
	const MANECTRIC   ; $136
	const PLUSLE      ; $137
	const MINUN       ; $138
	const VOLBEAT     ; $139
	const ILLUMISE    ; $13A
	const ROSELIA     ; $13B
	const GULPIN      ; $13C
	const SWALOT      ; $13D
	const CARVANHA    ; $13E
	const SHARPEDO    ; $13F
	const WAILMER     ; $140
	const WAILORD     ; $141
	const NUMEL       ; $142
	const CAMERUPT    ; $143
	const TORKOAL     ; $144
	const SPOINK      ; $145
	const GRUMPIG     ; $146
	const SPINDA      ; $147
	const TRAPINCH    ; $148
	const VIBRAVA     ; $149
	const FLYGON      ; $14A
	const CACNEA      ; $14B
	const CACTURNE    ; $14C
	const SWABLU      ; $14D
	const ALTARIA     ; $14E
	const ZANGOOSE    ; $14F
	const SEVIPER     ; $150
	const LUNATONE    ; $151
	const SOLROCK     ; $152
	const BARBOACH    ; $153
	const WHISCASH    ; $154
	const CORPHISH    ; $155
	const CRAWDAUNT   ; $156
	const BALTOY      ; $157
	const CLAYDOL     ; $158
	const LILEEP      ; $159
	const CRADILY     ; $15A
	const ANORITH     ; $15B
	const ARMALDO     ; $15C
	const FEEBAS      ; $15D
	const MILOTIC     ; $15E
	const CASTFORM    ; $15F
	const KECLEON     ; $160
	const SHUPPET     ; $161
	const BANETTE     ; $162
	const DUSKULL     ; $163
	const DUSCLOPS    ; $164
	const TROPIUS     ; $165
	const CHIMECHO    ; $166
	const ABSOL       ; $167
	const WYNAUT      ; $168
	const SNORUNT     ; $169
	const GLALIE      ; $16A
	const SPHEAL      ; $16B
	const SEALEO      ; $16C
	const WALREIN     ; $16D
	const CLAMPERL    ; $16E
	const HUNTAIL     ; $16F
	const GOREBYSS    ; $170
	const RELICANTH   ; $171
	const LUVDISC     ; $172
	const BAGON       ; $173
	const SHELGON     ; $174
	const SALAMENCE   ; $175
	const BELDUM      ; $176
	const METANG      ; $177
	const METAGROSS   ; $178
	const REGIROCK    ; $179
	const REGICE      ; $17A
	const REGISTEEL   ; $17B
	const LATIAS      ; $17C
	const LATIOS      ; $17D
	const KYOGRE      ; $17E
	const GROUDON     ; $17F
	const RAYQUAZA    ; $180
	const JIRACHI     ; $181
	const DEOXYS      ; $182

DEF NUM_POKEMON EQU 386
