STAGE_RED_FIELD_TOP       EQU $0
STAGE_RED_FIELD_BOTTOM    EQU $1
STAGE_BLUE_FIELD_TOP      EQU $2
STAGE_BLUE_FIELD_BOTTOM   EQU $3
STAGE_GOLD_FIELD_TOP      EQU $4
STAGE_GOLD_FIELD_BOTTOM   EQU $5
STAGE_SILVER_FIELD_TOP    EQU $6
STAGE_SILVER_FIELD_BOTTOM EQU $7

STAGE_FIRST_BONUS_STAGE   EQU $8
; STAGE_GENGAR_BONUS      EQU $8  ; buggy
STAGE_GENGAR_BONUS        EQU $9
; STAGE_MEWTWO_BONUS      EQU $a  ; buggy
STAGE_MEWTWO_BONUS        EQU $b
; STAGE_MEOWTH_BONUS      EQU $c  ; buggy
STAGE_MEOWTH_BONUS        EQU $d
; STAGE_DIGLETT_BONUS     EQU $e  ; buggy
STAGE_DIGLETT_BONUS       EQU $f
; STAGE_SEEL_BONUS        EQU $10  ; buggy
STAGE_SEEL_BONUS          EQU $11
