STAGE_RED_FIELD_TOP       EQU $0
STAGE_RED_FIELD_BOTTOM    EQU $1
STAGE_BLUE_FIELD_TOP      EQU $2
STAGE_BLUE_FIELD_BOTTOM   EQU $3
STAGE_GOLD_FIELD_TOP      EQU $4
STAGE_GOLD_FIELD_BOTTOM   EQU $5
STAGE_SILVER_FIELD_TOP    EQU $6
STAGE_SILVER_FIELD_BOTTOM EQU $7

FIRST_BONUS_STAGE         EQU $8
; STAGE_GENGAR_BONUS      EQU $8  ; unused top
STAGE_GENGAR_BONUS        EQU $9
; STAGE_MEWTWO_BONUS      EQU $a  ; unused top
STAGE_MEWTWO_BONUS        EQU $b
; STAGE_MEOWTH_BONUS      EQU $c  ; unused top
STAGE_MEOWTH_BONUS        EQU $d
; STAGE_DIGLETT_BONUS     EQU $e  ; unused top
STAGE_DIGLETT_BONUS       EQU $f
; STAGE_SEEL_BONUS        EQU $10 ; unused top
STAGE_SEEL_BONUS          EQU $11
; STAGE_UNOWN_BONUS       EQU $12 ; unused top
STAGE_UNOWN_BONUS         EQU $13
