DEF STAGE_RED_FIELD_TOP         EQU $0
DEF STAGE_RED_FIELD_BOTTOM      EQU $1
DEF STAGE_BLUE_FIELD_TOP        EQU $2
DEF STAGE_BLUE_FIELD_BOTTOM     EQU $3
DEF STAGE_GOLD_FIELD_TOP        EQU $4
DEF STAGE_GOLD_FIELD_BOTTOM     EQU $5
DEF STAGE_SILVER_FIELD_TOP      EQU $6
DEF STAGE_SILVER_FIELD_BOTTOM   EQU $7
DEF STAGE_RUBY_FIELD_TOP        EQU $8
DEF STAGE_RUBY_FIELD_BOTTOM     EQU $9
DEF STAGE_SAPPHIRE_FIELD_TOP    EQU $A
DEF STAGE_SAPPHIRE_FIELD_BOTTOM EQU $B

DEF FIRST_BONUS_STAGE         EQU $C
; STAGE_GENGAR_BONUS      EQU $C   ; buggy
DEF STAGE_GENGAR_BONUS        EQU $D
; STAGE_MEWTWO_BONUS      EQU $E   ; buggy
DEF STAGE_MEWTWO_BONUS        EQU $F
; STAGE_MEOWTH_BONUS      EQU $10  ; buggy
DEF STAGE_MEOWTH_BONUS        EQU $11
; STAGE_DIGLETT_BONUS     EQU $12  ; buggy
DEF STAGE_DIGLETT_BONUS       EQU $13
; STAGE_SEEL_BONUS        EQU $14  ; buggy
DEF STAGE_SEEL_BONUS          EQU $15
